name: Remote Update (VPS)

on:
  push:
    branches:
      - main  # Trigger only on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Load the environment
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            # Add common paths (just in case)
            export PATH=$PATH:/usr/local/bin:/usr/bin:/root/.local/share/pnpm
            
            # Navigate to the directory and Execute
            cd /var/www/repo-gender-reveal-bingo-party/project-files
            git pull origin main
            pnpm install
            pm2 restart gender-bingo --update-env
